apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --build local
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: flights
    app: pov-sim
    component: flights
  name: flights
spec:
  type: LoadBalancer
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    component: flights
